// <auto-generated />
using AcademicsWebsiteProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcademicsWebsiteProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240830113928_mg24")]
    partial class mg24
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcademicsWebsiteProject.Models.AddCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoursPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoLink1")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink10")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink11")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink12")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink13")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink14")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink15")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink2")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink3")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink4")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink5")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink6")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink7")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink8")
                        .HasColumnType("int");

                    b.Property<int>("VideoLink9")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("addCourse");
                });

            modelBuilder.Entity("AcademicsWebsiteProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
